namespace: home

replicaCount: 2

image:
  repository: 351381968847.dkr.ecr.us-east-2.amazonaws.com/xmaxx/home
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

imageAutomation:
  enabled: true
  schedule: "*/5 * * * *"
  awsRegion: us-east-2
  checkerImage: public.ecr.aws/aws-cli/aws-cli:2.27.37
  kubectlVersion: v1.32.3

service:
  port: 80

apiBackend:
  enabled: true
  pathPrefix: /api
  serviceName: home-backend
  servicePort: 8000

ingress:
  className: traefik
  hosts:
    - xmaxx.ai
  tls:
    enabled: true
    secretName: ""
    certResolver: letsencrypt

resources: {}
