namespace: home

replicaCount: 2

image:
  repository: athenalive/home
  tag: latest
  pullPolicy: Always

service:
  port: 80

apiBackend:
  enabled: true
  pathPrefix: /api
  serviceName: home-backend
  servicePort: 8000

ingress:
  className: traefik
  hosts:
    - xmaxx.ai
  tls:
    enabled: true
    secretName: ""
    certResolver: letsencrypt

resources: {}
