apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | quote }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | quote }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.secrets.githubOauthClientId | quote }}
  GITHUB_OAUTH_CLIENT_SECRET: |-
{{ .Values.secrets.githubOauthClientSecret | indent 4 }}
