apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "home-backend.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
