# Generated by Django 4.2.25 on 2026-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('auth_email', models.EmailField(blank=True, max_length=254)),
                ('auth_login', models.CharField(blank=True, max_length=255)),
                ('auth_name', models.CharField(blank=True, max_length=255)),
                ('auth_avatar_url', models.URLField(blank=True)),
                ('auth_profile_url', models.URLField(blank=True)),
                ('display_name', models.CharField(max_length=120)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='home_api_profile_provider_user_unique'),
        ),
    ]
