# Generated by Django 4.2.25 on 2026-03-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('token_key', models.CharField(max_length=20, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_suffix', models.CharField(max_length=4)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_user_id'], name='home_api_token_owner_idx')],
            },
        ),
    ]
