apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "home.fullname" . }}-websecure
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.certResolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.ingress.tls.certResolver | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.secretName }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "home.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
